### ISSUE TITLE
Add XML utilities

### ISSUE THREAD

**Issue by greenlaw110** [osglworks/java-tool#179]
The XML utilities provides method to manipulate XML data:
* read string to XML document
* print XML document to string

The XML utility shall plug into the osgl type convert framework and IO framework

**Comment by CrossLee** [comment]
`String s = "<xml><ToUserName><![CDATA[gh_703c945c39bf]]></ToUserName>
<FromUserName><![CDATA[oi-Xb5qca0FuQcsIdZcQhFVfyQvI]]></FromUserName>
<CreateTime>1555907217</CreateTime>
<MsgType><![CDATA[voice]]></MsgType>
<MediaId><![CDATA[eLNBbwouHdM4Hska9gfAnlG1x5X0dGfqyXIDr-nkeB1DGjhwqwlVW51Xt1OyCGfW]]></MediaId>
<Format><![CDATA[amr]]></Format>
<MsgId>6682570612625375232</MsgId>
<Recognition><![CDATA[hi。]]></Recognition>
</xml>"

Document doc = XML.read(xml);
logger.debug(doc.getElementsByTagName("FromUserName").item(0).toString());`

返回null。

**Comment by CrossLee** [comment]
`
<xml><ToUserName><![CDATA[gh_703c945c39bf]]></ToUserName>
<FromUserName><![CDATA[oi-Xb5qca0FuQcsIdZcQhFVfyQvI]]></FromUserName>
<CreateTime>1555907601</CreateTime>
<MsgType><![CDATA[voice]]></MsgType>
<MediaId><![CDATA[xfm3BIdKtzCI8hZc_vERjggM6sI3nFYgNbK3hNL6686kDm3pE_v3ElfXmXwCME4l]]></MediaId>
<Format><![CDATA[amr]]></Format>
<MsgId>6682572261892816896</MsgId>
<Recognition><![CDATA[今天天气不错。]]></Recognition>
</xml>
`

**Comment by greenlaw110** [comment]
@CrossLee can you create an new issue for this?
