### ISSUE TITLE
XML utilities enhancement

### ISSUE THREAD

**Issue by CrossLee** [osglworks/java-tool#203]
![image](https://user-images.githubusercontent.com/4584905/56863967-bb2e8880-69ef-11e9-9e59-8a1243b45bcf.png)

`
<xml><ToUserName><![CDATA[gh_703c945c39bf]]></ToUserName>
<FromUserName><![CDATA[oi-Xb5qca0FuQcsIdZcQhFVfyQvI]]></FromUserName>
<CreateTime>1555907601</CreateTime>
<MsgType><![CDATA[voice]]></MsgType>
<MediaId><![CDATA[xfm3BIdKtzCI8hZc_vERjggM6sI3nFYgNbK3hNL6686kDm3pE_v3ElfXmXwCME4l]]></MediaId>
<Format><![CDATA[amr]]></Format>
<MsgId>6682572261892816896</MsgId>
<Recognition><![CDATA[今天天气不错。]]></Recognition>
</xml>
`

上面那个xml字符串
Document doc = XML.read(xml);
logger.debug(doc.getElementsByTagName("FromUserName").item(0).toString());

返回null。

希望支持解析微信平台的xml格式。

**Comment by greenlaw110** [comment]
Cannot reproduce. Refer to https://github.com/osglworks/java-tool/blob/master/src/test/java/org/osgl/issues/Gh203.java

**Comment by CrossLee** [comment]
好奇怪，之前测试怎么都是返回null，这次测试又没问题了，issue可以关了。
